### ISSUE TITLE
请问支持舞萌旧框吗

### ISSUE THREAD

**Issue by Zhaocaizhiyuan** [RinNET-OpenSource/aqua_viewer#5]
本地这里机厅老板买了一台旧框，是精文框，准备改成Finale，想问一下Rin Net支不支持旧框

**Comment by tem-bili** [comment]
不支持旧框

**Comment by Zhaocaizhiyuan** [comment]
谢谢，麻烦您了2024年8月11日 下午10:50，tem-bili ***@***.***>写道：
不支持旧框
